name: Fix workflow
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (number)"
        required: true

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: get repository
        uses: actions/checkout@v4
        with:
          ref: releases/v${{ github.event.inputs.release_version }}
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: get repository
        uses: actions/checkout@v4
      - name: setup dependencies
        run: npm ci
      - name: run tests
        run: npm run test
      - name: run lint
        run: npm run lint
  Build-and-push-image-to-Yandex-Cloud-Container-Registry:
    runs-on: ubuntu-latest
    needs: test-lint
    steps:
      - name: get repository
        uses: actions/checkout@v4
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          VERSION_RELISE: ${{ github.event.inputs.release_version }}
        run: |
          docker build -t cr.yandex/${{vars.CR_REGISTRY}}/${{vars.CR_REPOSITORY}}:${{env.VERSION_RELISE}}_fix -t cr.yandex/${{vars.CR_REGISTRY}}/${{vars.CR_REPOSITORY}}:${{env.VERSION_RELISE}}_latest -f ./Dockerfile.shir-infra .
          docker push cr.yandex/${{vars.CR_REGISTRY}}/${{vars.CR_REPOSITORY}} --all-tags
      - name: Create tag
        run: |
          git tag v${{env.VERSION_RELISE}}_fix${{ github.run_number }}
          git push origin v${{ env.VERSION_RELISE }}_fix${{ github.run_number }}
